project:
  type: website

highlight-style: a11y

website:
  title: "Microcontrollers for Health & Agriculture"
  navbar:
    background: primary
    logo: figures/logo/SLUBI_logo.png
    left:
      - text: "About the course"
        href: index.qmd
      - text: "Pre-course lectures"
        menu:
          - text: "1. Microcontrollers, Sensors & Actuators"
            href: lecture1.qmd
          - text: "↳ Explore the micro:bit"
            href: microbit_explorer.qmd
          - text: "2. Programming with MakeCode"
            href: lecture2.qmd
          - text: "3. The Elecfreaks Smart Health Kit"
            href: lecture3.qmd
      - text: "Exercises"
        menu:
          - text: "Setup & overview"
            href: exercise_setup.qmd
          - text: "1. Push the button"
            href: exercise1.qmd
          - text: "2. Emergency call button"
            href: exercise2.qmd
          - text: "3. Environmental monitor"
            href: exercise3.qmd
          - text: "4. Irrigation alarm"
            href: exercise4.qmd
          - text: "★ Mini challenge"
            href: mini_challenge.qmd
          - text: "Bonus exercises"
            href: bonus_exercises.qmd
      - text: "Troubleshooting"
        href: troubleshooting.qmd
    tools:
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/amrei-bp/microcontroller_programming
          - text: Report an Issue
            href: https://github.com/amrei-bp/microcontroller_programming/issues
  search:
    location: navbar
    type: textbox

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true
    include-after-body: _includes/persist-inputs.html

execute:
  freeze: auto
